apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana

    spec:
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana:9.0.2
        ports:
        - containerPort: 5601
        env:
        - name: ELASTICSEARCH_HOSTS
          value: http://elasticsearch:9200
        - name: XPACK_SECURITY_ENABLED
          value: "false"
        - name: SERVER_PUBLICBASEURL
          value: http://localhost:5601
        - name: XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY
          value: "76edf678e61e6fa111397f3b4f227df3"
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: NodePort
  selector:
    app: kibana
  ports:
  - port: 5601
    targetPort: 5601
    nodePort: 30561

